---
functional:
  - Пользователь должен иметь возможность в настройках профиля сменить аватар и email
  - Сайт должен иметь чаты для общения пользователей (общий, в игре, личный)
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен работать при низкой скорости интернета
  - Сохраняется прогресс пользователя и прогресс текущих игр при разрыве связи
  - Подтверждение email при регистрации нового пользователя
implicit:
  - Сайт должен поддерживать возможность использовать популярные языки программирования
  - Сайт должен иметь возможность модерации
  - Сайт должен иметь обучающий режим для нового пользователя
  - Сайт должен иметь справочный раздел (возможности, правила игры)
  - Сайт должен иметь информационный блок, содержащий эмблемы и названия всех доступных языков программирования
